// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRK_WYf1FiLFJg36xOyHx4eIVlQtUiWBw',
    appId: '1:484329945408:web:462d83c94067a0a538e2a5',
    messagingSenderId: '484329945408',
    projectId: 'after-storm-64d13',
    authDomain: 'after-storm-64d13.firebaseapp.com',
    storageBucket: 'after-storm-64d13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3hWmUvFyrR2hAjCSJl0Xtl8mIJG9CSco',
    appId: '1:484329945408:android:b8c522107dd9e47438e2a5',
    messagingSenderId: '484329945408',
    projectId: 'after-storm-64d13',
    storageBucket: 'after-storm-64d13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXvC7kNe05QYV6y1jgPkad7_NXb234yzo',
    appId: '1:484329945408:ios:b189d37c2ebb26a138e2a5',
    messagingSenderId: '484329945408',
    projectId: 'after-storm-64d13',
    storageBucket: 'after-storm-64d13.firebasestorage.app',
    iosBundleId: 'com.example.afterStorm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXvC7kNe05QYV6y1jgPkad7_NXb234yzo',
    appId: '1:484329945408:ios:b189d37c2ebb26a138e2a5',
    messagingSenderId: '484329945408',
    projectId: 'after-storm-64d13',
    storageBucket: 'after-storm-64d13.firebasestorage.app',
    iosBundleId: 'com.example.afterStorm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRK_WYf1FiLFJg36xOyHx4eIVlQtUiWBw',
    appId: '1:484329945408:web:6da201da040e704638e2a5',
    messagingSenderId: '484329945408',
    projectId: 'after-storm-64d13',
    authDomain: 'after-storm-64d13.firebaseapp.com',
    storageBucket: 'after-storm-64d13.firebasestorage.app',
  );
}
